### PR TITLE
Work on completing the branch

### PR DESCRIPTION
**Pull request by rhc54**
Replace tabs with spaces per coding standards. Take a first cut at filling in missing data - we clearly will need to sense a few more things during the tests

### CODE REVIEW

**Comment by rhc54** [comment]
@jjhursey I know I don't have this PR setup correctly, but I'm not sure how to get it there. Any suggestions are welcome, or you can just try to "pull" the one commit I added at the end

**Comment by jjhursey** [comment]
I sync'ed my branch with the master branch. I saw you pushed some of the changes from this PR to the master. Is this PR still necessary? (are there additional changes here that didn't make it back to master?)

**Comment by rhc54** [comment]
only the last one where I updated IUDatabase.py, but you could just grab those separately

**Comment by jjhursey** [comment]
I just cherry-picked that commit from your branch and pushed it to mine (https://github.com/jjhursey/mtt-modern/commit/3241e4af967ca7e4a11dde7b45e75c5386e5a974)

Thanks!

**Pull request closed without merging**
